<?xml version="1.0" encoding="UTF-8" ?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="Ancabot">

    <!-- parameters -->
    <xacro:property     name="body_length"      value="0.2425"/>
    <xacro:property     name="body_width"       value="0.1525"/>
    <xacro:property     name="body_height"      value="0.0405"/>
    <xacro:property     name="coxa_length"      value="0.0"/>
    <xacro:property     name="femur_length"     value="0.0"/>
    <xacro:property     name="tibia_length"     value="0.0"/>
    <xacro:property     name="ground_offset"    value="0.064" />

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/Ancabot</robotNamespace>
        </plugin>
    </gazebo>

    <link name="base_link"/>

    <link name="body_link">
        <visual>
            <origin xyz="${body_width/2} ${-body_length/2} ${body_height/2}" rpy="0.0 ${pi} 0.0"/>
            <geometry>
                <mesh filename="package://hexapod_description/meshes/body.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="">
                <color rgba="0.7 0.7 0.7 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${body_width} ${body_length} ${body_height}"/>
            </geometry>
            <material name="">
                <color rgba="0.7 0.7 0.7 1"/>
            </material>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <mass value="0.00001"/>
            <inertia
                ixx="1.0" ixy="0.0"  ixz="0.0"
                iyy="1.0" iyz="0.0"
                izz="1.0" />
        </inertial>
    </link>
    <gazebo reference="body_link">
        <material>Gazebo/DarkGrey</material>
    </gazebo>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="body_link"/>
        <origin xyz="0.0 0.0 ${ground_offset}" rpy="0.0 0.0 0.0"/>
    </joint>

    <!-- Joint properties -->
    <xacro:property name="joint_lower_limit" value="-${3.14}"/>
    <xacro:property name="joint_upper_limit" value="${3.14}"/>
    <xacro:property name="joint_effort" value="6.0"/>
    <xacro:property name="joint_velocity" value="0.524"/>

    <!-- Leg macro -->
    <xacro:macro name="leg" params="side position x y angle axis">

        <!-- leg position -->
        <joint name="leg_center_joint_${side}${position}" type="fixed">
            <origin xyz="${x} ${y} 0.0" rpy="0.0 0.0 0.0"/>
            <parent link="body_link"/>
            <child link="leg_center_${side}${position}"/>
        </joint>
        <link name="leg_center_${side}${position}">
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <mass value="0.00001"/>
                <inertia
                    ixx="1.0" ixy="0.0"  ixz="0.0"
                    iyy="1.0" iyz="0.0"
                    izz="1.0" />
            </inertial>
        </link>

        <!-- coxa -->
        <joint name="coxa_joint_${side}${position}" type="revolute">
            <origin xyz="0.0 0.0 ${-body_height}" rpy="0.0 0.0 ${angle}"/>
            <parent link="leg_center_${side}${position}"/>
            <child link="coxa_${side}${position}"/>
            <axis xyz="0.0 0.0 1.0"/>
            <limit lower="${joint_lower_limit}" upper="${joint_upper_limit}" effort="${joint_effort}" velocity="${joint_velocity}"/>
        </joint>
        <transmission name="coxa_transmission_${side}${position}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="coxa_joint_${side}${position}">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="coxa_motor_${side}${position}">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
        <link name="coxa_${side}${position}">
            <visual>
                <origin xyz="0.035 0.02 0.02" rpy="${-pi/2} 0.0 ${pi}"/>
                <geometry>
                    <mesh filename="package://hexapod_description/meshes/coxa.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="">
                    <color rgba="0.7 0.7 0.7 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.015 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <box size="0.05 0.04 0.035"/>
                </geometry>
                <material name="">
                    <color rgba="0.7 0.7 0.7 1" />
                </material>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <mass value="0.00001"/>
                <inertia
                    ixx="1.0" ixy="0.0"  ixz="0.0"
                    iyy="1.0" iyz="0.0"
                    izz="1.0" />
            </inertial>
        </link>
        <gazebo reference="coxa_${side}${position}">
            <material>Gazebo/DarkGrey</material>
        </gazebo>

    </xacro:macro>

    <!-- Build robot model -->
    <xacro:leg side="R"     position="R"    x="-0.05825"   y="0.0935"     angle="${pi*3/4}"     axis="1"/>
    <xacro:leg side="R"     position="M"    x="-0.06225"   y="0.0250"     angle="${-pi}"      axis="1"/>
    <xacro:leg side="R"     position="F"    x="-0.05825"   y="-0.0435"    angle="${-pi*3/4}"    axis="1"/>

    <xacro:leg side="L"     position="R"    x="0.05825"    y="0.0935"     angle="${pi/4}"       axis="-1"/>
    <xacro:leg side="L"     position="M"    x="0.06225"    y="0.0250"     angle="${-pi*2}"       axis="-1"/>
    <xacro:leg side="L"     position="F"    x="0.05825"    y="-0.0435"    angle="${-pi/4}"      axis="-1"/>

</robot>